version: '3.1'

services:
  web:
    build: .
    ports:
      - "8000:8000"
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    environment:
      - XDEBUG_CONFIG=remote_host=localhost
    networks:
      - backend

  db:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=producty
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - backend

networks:
  backend:

volumes:
  database: